# Generated by Django 5.0.6 on 2024-06-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
