# Generated by Django 5.0.6 on 2024-06-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about_product', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.IntegerField(default=100)),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
